// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "driftdetector/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// IProvider is an autogenerated mock type for the IProvider type
type IProvider struct {
	mock.Mock
}

// ParseHCLConfig provides a mock function with given fields: configPath
func (_m *IProvider) ParseHCLConfig(configPath string) (*models.InstanceDetails, error) {
	ret := _m.Called(configPath)

	if len(ret) == 0 {
		panic("no return value specified for ParseHCLConfig")
	}

	var r0 *models.InstanceDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.InstanceDetails, error)); ok {
		return rf(configPath)
	}
	if rf, ok := ret.Get(0).(func(string) *models.InstanceDetails); ok {
		r0 = rf(configPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InstanceDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(configPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIProvider creates a new instance of IProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProvider {
	mock := &IProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
