// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	driftcheck "driftdetector/internal/driftcheck"

	mock "github.com/stretchr/testify/mock"

	report "driftdetector/internal/driftcheck/report"
)

// IPrinter is an autogenerated mock type for the IPrinter type
type IPrinter struct {
	mock.Mock
}

// PrintReport provides a mock function with given fields: instanceID, drifts, format
func (_m *IPrinter) PrintReport(instanceID string, drifts []driftcheck.Drift, format report.OutputFormatType) error {
	ret := _m.Called(instanceID, drifts, format)

	if len(ret) == 0 {
		panic("no return value specified for PrintReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []driftcheck.Drift, report.OutputFormatType) error); ok {
		r0 = rf(instanceID, drifts, format)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIPrinter creates a new instance of IPrinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPrinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPrinter {
	mock := &IPrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
